import React,{useState, useEffect} from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const [awardsList, setAwardsList] = useState([])
  const [selectedItems,setSelectedItems] = useState([])
  async function getAwardsList(){
    const res = await fetch('http://localhost:3000/api/ballots')
    const list = await res.json()
    setAwardsList(list.items)
  }

  useEffect(()=>{
    getAwardsList()    
  },[])
  useEffect(()=>{
    console.log("selectedItems")
  },[selectedItems])

  const handleItemSelection =(nomineeid,categoryid)=>{
    console.log(nomineeid,categoryid)
   //debugger
    let newSelectedItems = [...selectedItems];
    let obj = {"catid":categoryid,"itemid" : nomineeid}
    let selectedItemIndex = newSelectedItems.findIndex(o=>o.catid === categoryid)
    if(selectedItemIndex >=0){

      newSelectedItems[selectedItemIndex]['itemid'] = nomineeid
      setSelectedItems([newSelectedItems])
    }else{
      newSelectedItems.push(obj)
      setSelectedItems([newSelectedItems])
    }
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Take Home Test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="row">
        <h3 className="title">
          AWARDS 2021
          {selectedItems}
        </h3>
        
        {awardsList.map(val=>{
          return (<>
                    <div className="category-title">
                        {val.title}
                    </div>
                    <div className="row">
                    {
                      val.items && val.items.map(nominee=>{
                        return(
                            <div className="col-4 col-s-12">
                              <div className="card active" onClick={()=>handleItemSelection(nominee.id,val.id)}>
                                <div>
                                  {nominee.title}
                                </div>
                                <div className="image-cropper">
                                  <img src={nominee.photoUrL} />
                                </div>
                                <div>
                                  <button>select</button>
                                </div>
                              </div>
                            </div>
                          
                        )
                      })
                    }
                    </div>
                  </>
                )
        })}
      </main>
    </div>
  )
}

export default Home
